//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace testwcf.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IEcompassService", Namespace="http://tempuri.org/")]
    public partial class EcompassService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SayHelloToOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProductsDataOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public EcompassService() {
            this.Url = global::testwcf.Properties.Settings.Default.testwcf_localhost_EcompassService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SayHelloToCompletedEventHandler SayHelloToCompleted;
        
        /// <remarks/>
        public event GetProductsDataCompletedEventHandler GetProductsDataCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IEcompassService/SayHelloTo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SayHelloTo() {
            object[] results = this.Invoke("SayHelloTo", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SayHelloToAsync() {
            this.SayHelloToAsync(null);
        }
        
        /// <remarks/>
        public void SayHelloToAsync(object userState) {
            if ((this.SayHelloToOperationCompleted == null)) {
                this.SayHelloToOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSayHelloToOperationCompleted);
            }
            this.InvokeAsync("SayHelloTo", new object[0], this.SayHelloToOperationCompleted, userState);
        }
        
        private void OnSayHelloToOperationCompleted(object arg) {
            if ((this.SayHelloToCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SayHelloToCompleted(this, new SayHelloToCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IEcompassService/GetProductsData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/EcompassService")]
        public PnpProducts[] GetProductsData() {
            object[] results = this.Invoke("GetProductsData", new object[0]);
            return ((PnpProducts[])(results[0]));
        }
        
        /// <remarks/>
        public void GetProductsDataAsync() {
            this.GetProductsDataAsync(null);
        }
        
        /// <remarks/>
        public void GetProductsDataAsync(object userState) {
            if ((this.GetProductsDataOperationCompleted == null)) {
                this.GetProductsDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProductsDataOperationCompleted);
            }
            this.InvokeAsync("GetProductsData", new object[0], this.GetProductsDataOperationCompleted, userState);
        }
        
        private void OnGetProductsDataOperationCompleted(object arg) {
            if ((this.GetProductsDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProductsDataCompleted(this, new GetProductsDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/EcompassService")]
    public partial class PnpProducts {
        
        private ProductCatagory catagoryField;
        
        private System.DateTime productDateEndPromoField;
        
        private bool productDateEndPromoFieldSpecified;
        
        private string productDescField;
        
        private double productDropPercentField;
        
        private bool productDropPercentFieldSpecified;
        
        private int productIDField;
        
        private bool productIDFieldSpecified;
        
        private string productImageField;
        
        private string productNameField;
        
        private float productPriceField;
        
        private bool productPriceFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ProductCatagory Catagory {
            get {
                return this.catagoryField;
            }
            set {
                this.catagoryField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ProductDateEndPromo {
            get {
                return this.productDateEndPromoField;
            }
            set {
                this.productDateEndPromoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProductDateEndPromoSpecified {
            get {
                return this.productDateEndPromoFieldSpecified;
            }
            set {
                this.productDateEndPromoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ProductDesc {
            get {
                return this.productDescField;
            }
            set {
                this.productDescField = value;
            }
        }
        
        /// <remarks/>
        public double ProductDropPercent {
            get {
                return this.productDropPercentField;
            }
            set {
                this.productDropPercentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProductDropPercentSpecified {
            get {
                return this.productDropPercentFieldSpecified;
            }
            set {
                this.productDropPercentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int ProductID {
            get {
                return this.productIDField;
            }
            set {
                this.productIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProductIDSpecified {
            get {
                return this.productIDFieldSpecified;
            }
            set {
                this.productIDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ProductImage {
            get {
                return this.productImageField;
            }
            set {
                this.productImageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ProductName {
            get {
                return this.productNameField;
            }
            set {
                this.productNameField = value;
            }
        }
        
        /// <remarks/>
        public float ProductPrice {
            get {
                return this.productPriceField;
            }
            set {
                this.productPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProductPriceSpecified {
            get {
                return this.productPriceFieldSpecified;
            }
            set {
                this.productPriceFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/EcompassService")]
    public partial class ProductCatagory {
        
        private string catagoryDescField;
        
        private string catagoryNameField;
        
        private int catagoryIDField;
        
        private bool catagoryIDFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CatagoryDesc {
            get {
                return this.catagoryDescField;
            }
            set {
                this.catagoryDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CatagoryName {
            get {
                return this.catagoryNameField;
            }
            set {
                this.catagoryNameField = value;
            }
        }
        
        /// <remarks/>
        public int catagoryID {
            get {
                return this.catagoryIDField;
            }
            set {
                this.catagoryIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool catagoryIDSpecified {
            get {
                return this.catagoryIDFieldSpecified;
            }
            set {
                this.catagoryIDFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void SayHelloToCompletedEventHandler(object sender, SayHelloToCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SayHelloToCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SayHelloToCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetProductsDataCompletedEventHandler(object sender, GetProductsDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProductsDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProductsDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PnpProducts[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PnpProducts[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591